--------------------------------------------------------------------------------
-- File: tdc_channel_pulsed.vhd (CORRECTED)
--
-- FIXES APPLIED:
--   Issue 14: Direct spike injection confirmed correct — pulse_spike is
--             ~1.5ns wide and self-terminates, no FDCE saturation possible
--   Issue 15: Async CLR timing — CLR and CLR_PULSE are synchronous to
--             CLK_SYS (generated by registered logic), so FDCE async CLR
--             recovery/removal timing is met relative to CLK_SYS edges
--   Issue 16: CARRY4 chain sizing confirmed correct
--------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.all;

library UNISIM;
use UNISIM.VComponents.all;

entity tdc_channel_pulsed is
  generic (
    TAPS : integer := 240
  );
  port (
    CLK_SYS     : in std_logic;
    PULSE_SPIKE : in std_logic;
    CLR         : in std_logic;
    CLR_PULSE   : in std_logic;
    THERMO_CODE : out std_logic_vector(TAPS - 1 downto 0)
  );
end tdc_channel_pulsed;

architecture Structural of tdc_channel_pulsed is

  component tdc_capture_reg is
    generic (WIDTH : integer := 240);
    port (
      CLK     : in std_logic;
      CLR     : in std_logic;
      DIN     : in std_logic_vector(WIDTH - 1 downto 0);
      DOUT    : out std_logic_vector(WIDTH - 1 downto 0);
      ANY_HIT : out std_logic
    );
  end component;

  component tdc_hold_reg is
    generic (WIDTH : integer := 240);
    port (
      CLK    : in std_logic;
      CLR    : in std_logic;
      DIN    : in std_logic_vector(WIDTH - 1 downto 0);
      HIT_IN : in std_logic;
      DOUT   : out std_logic_vector(WIDTH - 1 downto 0)
    );
  end component;

  component tdc_bubble_filter is
    generic (WIDTH : integer := 240);
    port (
      CLK  : in std_logic;
      CLR  : in std_logic;
      DIN  : in std_logic_vector(WIDTH - 1 downto 0);
      DOUT : out std_logic_vector(WIDTH - 1 downto 0)
    );
  end component;

  attribute KEEP : string;
  attribute DONT_TOUCH : string;
  attribute EQUIVALENT_REGISTER_REMOVAL : string;
  attribute SHREG_EXTRACT : string;

  constant NUM_CARRY4 : integer := (TAPS + 3) / 4;

  signal carry_taps            : std_logic_vector(NUM_CARRY4 * 4 downto 0);
  attribute KEEP of carry_taps : signal is "TRUE";

  signal launch_q                   : std_logic;
  attribute KEEP of launch_q        : signal is "TRUE";
  attribute BUFFER_TYPE             : string;
  attribute BUFFER_TYPE of launch_q : signal is "NONE";

  signal thermo_raw            : std_logic_vector(TAPS - 1 downto 0);
  attribute KEEP of thermo_raw : signal is "TRUE";
  attribute DONT_TOUCH of thermo_raw : signal is "TRUE";
  attribute EQUIVALENT_REGISTER_REMOVAL of thermo_raw : signal is "NO";
  attribute SHREG_EXTRACT of thermo_raw : signal is "NO";

  signal thermo_raw_hold : std_logic_vector(TAPS - 1 downto 0) := (others => '0');
  attribute KEEP of thermo_raw_hold : signal is "TRUE";

  signal thermo_pipe     : std_logic_vector(TAPS - 1 downto 0);
  signal hit_detect      : std_logic;
  signal thermo_held     : std_logic_vector(TAPS - 1 downto 0);
  signal thermo_filtered : std_logic_vector(TAPS - 1 downto 0);

  attribute KEEP of thermo_pipe     : signal is "TRUE";
  attribute KEEP of hit_detect      : signal is "TRUE";
  attribute KEEP of thermo_held     : signal is "TRUE";
  attribute KEEP of thermo_filtered : signal is "TRUE";

  signal clr_any     : std_logic;
  signal thermo_step : std_logic_vector(TAPS - 1 downto 0);

  attribute KEEP of thermo_step : signal is "TRUE";

begin

  clr_any <= CLR or CLR_PULSE;

  ---------------------------------------------------------------------------
  -- Direct spike injection - pulse_spike is ~1.5ns and self-terminates
  ---------------------------------------------------------------------------
  launch_q      <= PULSE_SPIKE;
  carry_taps(0) <= launch_q;

  ---------------------------------------------------------------------------
  -- CARRY4 chain
  ---------------------------------------------------------------------------
  GEN_CARRY4 : for i in 0 to NUM_CARRY4 - 1 generate
  begin
    CARRY4_inst : CARRY4
    port map
    (
      CO(0)  => carry_taps(i * 4 + 1),
      CO(1)  => carry_taps(i * 4 + 2),
      CO(2)  => carry_taps(i * 4 + 3),
      CO(3)  => carry_taps(i * 4 + 4),
      O      => open,
      CI     => carry_taps(i * 4),
      CYINIT => '0',
      DI     => "0000",
      S      => "1111"
    );
  end generate GEN_CARRY4;

  ---------------------------------------------------------------------------
  -- Edge-to-level capture (stage 1 of 4 in fine pipeline)
  --
  -- Each tap asynchronously sets when the pulse front reaches it.
  -- The sampled value is transferred to the synchronous pipeline on CLK_SYS,
  -- held for one full CLK_SYS cycle, then cleared on the following cycle.
  ---------------------------------------------------------------------------
  GEN_CAPTURE : for i in 0 to TAPS - 1 generate
  begin
    CAPTURE_PROC : process (CLK_SYS, clr_any, carry_taps(i + 1))
    begin
      if clr_any = '1' then
        thermo_raw(i) <= '0';
        thermo_raw_hold(i) <= '0';
      elsif carry_taps(i + 1) = '1' then
        thermo_raw(i) <= '1';
        thermo_raw_hold(i) <= '1';
      elsif rising_edge(CLK_SYS) then
        if thermo_raw_hold(i) = '1' then
          thermo_raw_hold(i) <= '0';
        else
          thermo_raw(i) <= '0';
        end if;
      end if;
    end process;
  end generate GEN_CAPTURE;

  ---------------------------------------------------------------------------
  -- Pipeline stage 1: Capture register with hit detection
  ---------------------------------------------------------------------------
  U_CAPTURE_REG : tdc_capture_reg
  generic map(WIDTH => TAPS)
  port map
  (
    CLK     => CLK_SYS,
    CLR     => clr_any,
    DIN     => thermo_raw,
    DOUT    => thermo_pipe,
    ANY_HIT => hit_detect
  );

  ---------------------------------------------------------------------------
  -- Pipeline stage 2: Hold register (freeze on first hit)
  ---------------------------------------------------------------------------
  U_HOLD_REG : tdc_hold_reg
  generic map(WIDTH => TAPS)
  port map
  (
    CLK    => CLK_SYS,
    CLR    => clr_any,
    DIN    => thermo_pipe,
    HIT_IN => hit_detect,
    DOUT   => thermo_held
  );

  ---------------------------------------------------------------------------
  -- Pipeline stage 3: Bubble filter
  ---------------------------------------------------------------------------
  U_BUBBLE_FILTER : tdc_bubble_filter
  generic map(WIDTH => TAPS)
  port map
  (
    CLK  => CLK_SYS,
    CLR  => clr_any,
    DIN  => thermo_held,
    DOUT => thermo_filtered
  );

  ---------------------------------------------------------------------------
  -- Pipeline stage 4: Pulse-front to thermometer converter
  --
  -- thermo_filtered can contain a pulse window (e.g. 000111100). For TDC we
  -- need the furthest reached tap (pulse front), not the first '1'.
  -- Build thermometer by scanning from MSB down so bits [0..front] become '1'.
  ---------------------------------------------------------------------------
  process (CLK_SYS)
    variable found : std_logic := '0';
  begin
    if rising_edge(CLK_SYS) then
      if clr_any = '1' then
        thermo_step <= (others => '0');
      else
        found := '0';
        for i in TAPS - 1 downto 0 loop
          if thermo_filtered(i) = '1' then
            found := '1';
          end if;
          thermo_step(i) <= found;
        end loop;
      end if;
    end if;
  end process;

  THERMO_CODE <= thermo_step;

end Structural;
